ratings/urls.py
from django.conf.urls import patterns, url

from ratings import views

urlpatterns = patterns('',
	url(r'^$', views.RestaurantList.as_view(), name='index'),
	url(r'^map/$', views.RestaurantListMap.as_view(), name='map'),
	url(r'^restaurant/(?P<pk>\d+)/$', views.RestaurantDetail.as_view(), name='restaurant_detail'),
	url(r'^restaurant/(?P<restaurant_id>\d+)/add_review/$', views.AddReview.as_view(), name='add_review'),
	url(r'^restaurant/(?P<restaurant_id>\d+)/update_review/(?P<pk>\d+)/$', views.UpdateReview.as_view(), name='update_review'),
	url(r'^restaurant/(?P<restaurant_id>\d+)/delete_review/(?P<pk>\d+)/$', views.DeleteReview.as_view(), name='delete_review'),
)

restaurant/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic import RedirectView
from ratings.views import MyRegistrationBackend
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'restaurant.views.home', name='home'),
    # url(r'^restaurant/', include('restaurant.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/', MyRegistrationBackend.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('ratings.urls', namespace="ratings")),
)

ratings/models.py
from django.db import models
from django.core.urlresolvers import reverse
from geopy import geocoders
from django.contrib.auth.models import User
# Create your models here.

class Restaurant(models.Model):
	name = models.CharField(max_length=100)
	address = models.CharField(max_length=100) 
	desc = models.TextField()
	city = models.CharField(max_length=100)
	state = models.CharField(max_length=15)
	zipcode = models.CharField(max_length=25)
	lat = models.CharField(max_length=20, editable=False, null=True, blank=True)
	lon = models.CharField(max_length=20, editable=False, null=True, blank=True)

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		addr = self.address
		city = self.city
		state = self.state
		g = geocoders.GoogleV3()
		place, (lat, lon) = g.geocode(str(addr) + " " + str(city) + " " + str(state))
		self.lat = lat
		self.lon = lon
		super(Restaurant, self).save(*args, **kwargs)

	@property
	def reviews(self):
		return Review.objects.all().filter(restaurant=self)
	
	@property
	def avg_rating(self):
		ratings = Review.objects.all().filter(restaurant=self)
		total_points = 0
		num = 0
		for rating in ratings:
			total_points += rating.rating*1.0
			num +=1
		return total_points/num

class Review(models.Model):
	name = models.ForeignKey(User)
	restaurant = models.ForeignKey(Restaurant)
	rating = models.IntegerField(help_text='out of 10')
	comment = models.TextField()

	def __unicode__(self):
		return "%s-%s" % (self.name, self.restaurant)

	def get_absolute_url(self):
		return reverse('ratings:restaurant_detail', args=(self.restaurant.id,))

ratings/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.admin import widgets
from ratings.models import *

class ReviewForm(ModelForm):
	class Meta:
		model = Review
		exclude = ('name','restaurant',)

ratings/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from registration.backends.simple.views import RegistrationView
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from endless_pagination.views import AjaxListView

from ratings.models import *
from ratings.forms import *

class RestaurantList(ListView):#possibly paginate this view
	model = Restaurant
	context_object_name = 'restaurants'
	template_name = 'ratings/index.html'

class RestaurantListMap(ListView):
	model = Restaurant
	context_object_name = 'restaurants'
	template_name = 'ratings/map.html'

class RestaurantDetail(DetailView):
	model = Restaurant
	context_object_name = 'restaurant'
	template_name = 'ratings/restaurant_detail.html'

	def get_context_data(self, **kwargs):
		user = self.request.user
		context = super(RestaurantDetail, self).get_context_data(**kwargs)
		context['user'] = user
		return context

class AddReview(CreateView):
	model = Review
	template_name = 'ratings/review_add.html'
	form_class = ReviewForm

	def get_form(self, form_class):
		user = self.request.user
		restaurant = get_object_or_404(Restaurant, pk = self.kwargs['restaurant_id'])
		form = super(AddReview, self).get_form(form_class)
		form.instance.name = user
		form.instance.restaurant = restaurant
		return form

	
	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(AddReview, self).dispatch(*args, **kwargs)

class UpdateReview(UpdateView):
	model = Review
	template_name = 'ratings/review_update.html'
	form_class = ReviewForm

	def get_context_data(self, **kwargs):
		user = self.request.user
		review = get_object_or_404(Review, pk = self.kwargs['pk'])
		cur_user = False
		if int(review.name.id) == int(user.id):
			cur_user = True
		context = super(UpdateReview, self).get_context_data(**kwargs)
		context['cur_user'] = cur_user
		return context


	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(UpdateReview, self).dispatch(*args, **kwargs)

class DeleteReview(DeleteView):
	model = Review
	success_url = reverse_lazy('ratings:index')

	def get_context_data(self, **kwargs):
		user = self.request.user
		review = get_object_or_404(Review, pk = self.kwargs['pk'])
		cur_user = False
		if int(review.name.id) == int(user.id):
			cur_user = True
		context = super(DeleteReview, self).get_context_data(**kwargs)
		context['cur_user'] = cur_user
		return context

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(DeleteReview, self).dispatch(*args, **kwargs)

class MyRegistrationBackend(RegistrationView):
    def get_success_url(self, request, user):
        return reverse('ratings:index')

ratings/templates/ratings/base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <meta charset="utf-8"> 
        <title>{% block title %}Rate a Restaurant{% endblock %}</title>
        <link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
        <link rel ="stylesheet" href="{% static 'style.css' %}">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
        <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
	<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB-A73teZ6WfI6kv9_RIU5SCoEPJjjX5bY&sensor=false">
    </script>
    
        {% block scripts %}{% endblock %}
</head>
<body>
        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
                <ul class="nav">
                  <li class="active">
                    <a class="brand" href="{% url 'ratings:index' %}">Rate a Restaurant</a>
                  </li>
		  <li><a href="{% url 'ratings:map' %}">Map</a></li>
		</ul>
		 <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span>Log In</a></li>
		    <li><a href="{% url 'registration_register' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                    {% endif %}
		    {% if user.is_superuser %}
		    <li><a href="{% url 'admin:app_list' 'ratings' %}">Admin</a></li>
		    {% endif %}
		    <li><a href="http://mysite.smg247.webfactional.com">Other Apps</a></li>
                </ul>
            </div>
          </div>
        </div> 
	<div class="content">
        {% block content %}

        {% endblock %}
	</div>
</body>

</html>

ratings/templates/ratings/index.html
{% extends 'ratings/base.html' %}



{% block content %}
<div class="box">
	<h1>Welcome to Rate a Restaurant</h1>
	<p>Here, you can view all of the restaurants in the St. George area and see their ratings according to guests just like you! You can also add your own ratings in order to help other guests find your favorite restaurant!</p>
	<h3>Restaurants in St. George, UT</h3>	
	<table class="table">
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th>Description</th>
		</tr>
		{% for restaurant in restaurants %}
			<tr>
				<td><a href="{%url 'ratings:restaurant_detail' restaurant.id %}">{{restaurant.name}}</a></td>
				<td>{{restaurant.address}} {{restaurant.city}}, {{restaurant.state}}  {{restaurant.zipcode}}</td>
				<td>{{restaurant.desc}}</td>
			</tr>
		{% endfor %}
	</table>

</div>
{% endblock %}

ratings/templates/ratings/map.html
{% extends 'ratings/base.html' %}

{% block scripts %}
<script type="text/javascript">
// This example displays a marker at the center of Australia.
// When the user clicks the marker, an info window opens.
 
function initialize() {
  var myLatlng = new google.maps.LatLng(37.1097967,-113.5641498);
  var mapOptions = {
    zoom: 12,
    center: myLatlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
 
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
 
  
{% for restaurant in restaurants %}
 
  var infowindow{{forloop.counter}} = new google.maps.InfoWindow({
      content: "<a href='{%url 'ratings:restaurant_detail' restaurant.id %}'>{{restaurant.name|safe}}</a> {% if restaurant.reviews %} <br /> Avg Rating: {{restaurant.avg_rating}}{% endif %}<br />{{restaurant.address}} {{restaurant.city}}  {{restaurant.zipcode}}<br />{{ restaurant.desc }}"
  });
  var marker{{forloop.counter}} = new google.maps.Marker({
      position: new google.maps.LatLng({{restaurant.lat}},{{restaurant.lon}}),
      map: map,
      title: "{{restaurant.name|safe}}"
  });
  google.maps.event.addListener(marker{{forloop.counter}}, 'click', function() {
    infowindow{{forloop.counter}}.open(map,marker{{forloop.counter}});
  });
{% endfor %}
}
 
google.maps.event.addDomListener(window, 'load', initialize);
 
</script>
{% endblock scripts %}

{% block content %}
	<h1>Map of Restaurant Locations</h1>

	<div id="map-canvas"/ style="width: 100%; height: 100%;">

{% endblock content %}

ratings/templates/ratings/restaurant_detail.html
{% extends 'ratings/base.html' %}



{% block content %}
	<div class="box">
	<h1>{{restaurant.name}}</h1>
	<h6>{{restaurant.address}}<br /> {{restaurant.city}}, {{restaurant.state}}  {{restaurant.zipcode}}</h6>
	<p>{{restaurant.desc}}</p>
	<h3>Customer Reviews</h3>
	<p><a href="{%url 'ratings:add_review' restaurant.id %}">Add a Review</a></p>
	{% if restaurant.reviews %}
	<h5>Average Rating:  {{restaurant.avg_rating}}/10</h5>
	
	<table class="table">
		<tr>
			<th>Reviewer</th>
			<th>Rating</th>
			<th>Comment</th>
			<th></th>
			<th></th>
		<tr>
		
		{% for review in restaurant.reviews %}
			<tr>
				<td>{{review.name}}</td>
				<td>{{review.rating}}/10</td>
				<td>{{review.comment}}</td>
				{% if user.id == review.name.id %}
					<td><a href="{% url 'ratings:update_review' restaurant.id review.id %}">Edit</a></td>
					<td><a href="{% url 'ratings:delete_review' restaurant.id review.id %}">Delete</a></td>
				{% else %}
					<td></td>
					<td></td>
				{% endif %}
			</tr>
		{% endfor %}
	{% endif %}
	</table>
	</div>
{% endblock %}

ratings/templates/ratings/review_add.html
{% extends "ratings/base.html" %}

{% block content %}
<div class="input box">
	<h1>Create a new review</h1>
	<form method="POST" action="." id="board-add-form">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Add Review"></input>
	</form>
</div>
{% endblock %}

ratings/templates/ratings/review_confirm_delete.html
{% extends "ratings/base.html" %}

{% block content %}
<div class="box">
	{% if cur_user %}
	<h1>Delete Review</h1>
	<form action="" method="post">{% csrf_token %}
    		<p>Are you sure you want to delete "{{ object }}"?</p>
    		<input type="submit" value="Confirm" />
	</form>
	{% else %}
		<h1>You do not own this review and therefore cannot delete it!</h1>
	{% endif %}
</div>
{% endblock %}

ratings/templates/ratings/review_update.html
{% extends "ratings/base.html" %}

{% block content %}
<div class="input box">
	{% if cur_user %}
	<h1>Update Review</h1>
	<form method="POST" action="." id="board-add-form">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Update Review"></input>
	</form>
	{% else %}
		<h1>You do not own this review and therefore cannot edit it!</h1>
	{% endif %}
</div>
{% endblock %}

restaurant/templates/base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
        <meta charset="utf-8"> 
        <title>{% block title %}Rate a Restaurant{% endblock %}</title>
        <link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
        <link rel ="stylesheet" href="{% static 'style.css' %}">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
        <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
        {% block scripts %}{% endblock %}
</head>
<body>
        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
                <ul class="nav">
                  <li class="active">
                    <a class="brand" href="{% url 'ratings:index' %}">Rate a Restaurant</a>
                  </li>
		</ul>
            </div>
          </div>
        </div> 
        <div class="content">
        {% block content %}

        {% endblock %}
               	<div class="footer">
                Created by: Stephen Goeddel<br />
                On: 11/20/2013
        </div>
        </div>

</body>

</html>